version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/usr/src/app

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    environment:
      NEXT_PUBLIC_SERVER: http://localhost:3001
    depends_on:
      - server
